//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyTitle("BSN.Commons.Orm.EntityFramework")]
[assembly: AssemblyDescription("ORM Helpers for using entity framework in enterprise application")]
[assembly: AssemblyCompany("BSN Company")]
[assembly: AssemblyProduct("BSN.Commons.Orm.EntityFramework")]
[assembly: AssemblyVersion("1.6.3")]
[assembly: AssemblyFileVersion("1.6.3")]
[assembly: AssemblyInformationalVersion("1.6.3")]
[assembly: AssemblyCopyright("Copyright ©  2020 BSN Co.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("20ebda57-83dc-4557-bbd2-535cf3c6751b")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]

