//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System;

[assembly: AssemblyTitle("BSN.Commons.Users")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("BSN.Commons.Users")]
[assembly: AssemblyVersion("1.9.0")]
[assembly: AssemblyFileVersion("1.9.0")]
[assembly: AssemblyInformationalVersion("1.9.0")]
[assembly: AssemblyCopyright("Copyright © 2022 BSN Co.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("213abcef-7e9a-4ce5-a3ef-289c9781344d")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]

